version: "3.9"
services:
  service:
    build: .
    working_dir: /app
    command: ['yarn', 'dev']
    volumes: 
      - .:/app
    ports:
      - "5002:80"
    networks:
      - auth-db-network
  auth-db:
    image: mongo
    container_name: auth-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - auth-db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - auth-db-network
  auth-mongo-express:
    image: mongo-express
    container_name: auth-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=auth-db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - auth-db-network
    depends_on:
      - auth-db
    ports:
      - "8081:8081"
volumes:
  auth-db-data:
    name: auth-db-data
networks:
  auth-db-network:
    name: auth-db-network
